version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

  # Backend API
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: task_manager
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your_super_secure_jwt_secret_key_here
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
    depends_on:
      - postgres
    networks:
      - task-manager-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:6000/api
    depends_on:
      - backend
    networks:
      - task-manager-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge
