apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-manager
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: umesh1212/backend-todo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: DB_PASSWORD
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: DB_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: JWT_EXPIRE
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: task-manager-config
              key: CLIENT_URL
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "100Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-manager
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
