apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "task_manager"
  DB_USER: "postgres"
  JWT_EXPIRE: "7d"
  CLIENT_URL: "https://task-manager.example.com"
  BACKEND_PORT: "5000"
  REACT_APP_API_URL: "https://api.task-manager.example.com/api"
