apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
data:
  NODE_ENV: "production"
  PORT: "8000"
  DB_HOST: "dpg-d253gj49c44c73b5tdfg-a.oregon-postgres.render.com"
  DB_PORT: "5432"
  DB_NAME: "postgress_sr1k"
  DB_USER: "postgress_sr1k_user"
  JWT_EXPIRE: "7d"
  CLIENT_URL: "http://localhost:3000"
  API_URL: "http://backend-service/api"
