apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'your-super-secure-jwt-secret-key' | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXk=
  # echo -n 'your-postgres-password' | base64
  DB_PASSWORD: WGs3U0RIZDlMWTc4Szk1SXF2MU1kRFAwcENjdHpWNVY=
  # echo -n 'postgresql://postgres:your-postgres-password@postgres-service:5432/task_manager' | base64
  DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzc19zcjFrX3VzZXI6WGs3U0RIZDlMWTc4Szk1SXF2MU1kRFAwcENjdHpWNVZAZHBnLWQyNTNnajQ5YzQ0YzczYjV0ZGZnLWEub3JlZ29uLXBvc3RncmVzLnJlbmRlci5jb20vcG9zdGdyZXNzX3NyMWs/c3NsbW9kZT1yZXF1aXJl
