apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'your-super-secure-jwt-secret-key' | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXk=
  # echo -n 'your-postgres-password' | base64
  DB_PASSWORD: eW91ci1wb3N0Z3Jlcy1wYXNzd29yZA==
  # echo -n 'postgresql://postgres:your-postgres-password@postgres-service:5432/task_manager' | base64
  DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnlvdXItcG9zdGdyZXMtcGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3Rhc2tfbWFuYWdlcg==
